{% set name = "django-annoying" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-annoying-{{ version }}.tar.gz
  sha256: d42a9f4757701903edcb3398c542e6d39e67856295059589296c277350d02fc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=1.11
    - six

test:
  imports:
    - annoying
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/skorokithakis/django-annoying
  summary: This is a django application that tries to eliminate annoying things in the Django framework.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
